### ISSUE TITLE
BDD Testing

### ISSUE THREAD

**Issue by sschweber** [rachitmehrotra1/devops-restapi#47]
As a developer
I need to write behaviour tests 
So that we can ensure our application is working properly

**Comment by sschweber** [comment]
Hey Team, I pushed this to a Branch bdd-testing. Can someone help me figure out why it's failing when I try to access '/users'? I'm getting an error that says: NameError: global name 'redis_server' is not defined.. if you pull from this branch and run the behave command you'll see what I'm talking about.

**Comment by rachitmehrotra1** [comment]
@sschweber  I think you are getting that error because the redis server is not working at the time the behave goes to users/ , i'm not certain of it.

You can look at this link https://github.com/rofrano/nyu-lab-bdd-tdd/blob/master/features/environment.py , this is what Professor has done and try if this works for you. Otherwise i think Carlos or Nihit might help us out with it. Otherwise we can check with professor over slack.

**Comment by rachitmehrotra1** [comment]
Plus in addition to that ,after looking at your code I believe that your function  ,  for 
https://github.com/rachitmehrotra1/devops-restapi/blob/bdd-testing/features/steps/steps.py#L23
is not correct.

I have created the environments.py and will push it to your branch so that you don't have to do that part :)

**Comment by sschweber** [comment]
@rachitmehrotra1 thanks for creating that file

I'm still getting the same error, although I think that my function is correct in the steps.py file, since that part is passing. it's "when I visit '/users'" that is failing because of the redis server error. The error is referring to line 292 in server.py saying that "redis_server" is not defined. Any idea how to fix that?

**Comment by rachitmehrotra1** [comment]
All Behave tests pass
